version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ../Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
      - logstash
    networks:
      - spring-boot-network

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cafemania
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  prometheus:
    image: prom/prometheus:v2.33.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:8.4.3
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  pghero:
    image: ankane/pghero
    ports:
      - 8081:8080
    environment:
      - PGHERO_DATABASE_URL=postgres://your-username:your-password@db:5432/your-database-name
    depends_on:
      - db

networks:
  spring-boot-network:
    driver: bridge